#!/usr/bin/env bash
# To display the file `/etc/passwd` contents.
#   Only username, user id, and user home directory path.

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
