#!/usr/bin/env bash
# To parse Apache log files in list format.
#   To group visitors by IP and HTTP status code.
#   To display number of occurrences, IP, and HTTP status
#   Code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
